#!/bin/bash
USAGE="You must pass in a link to a page with a video in it"
if [ $# -lt 1 ];
then
	echo $USAGE
	exit 2
elif [ $# -gt 1 ];
then
	echo "Too many arguments"
	echo $USAGE
	exit 2
fi
youtube-dl --extract-audio --audio-format mp3 --ignore-errors --output '~/Music/%(title)s.%(ext)s' $1